### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by dmange3190** [infosecB/detection-as-code#1]
I am getting warning. 
WARN[0000] The "EXTERNAL_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEFAULT_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEFAULT_PASSWORD" variable is not set. Defaulting to a blank string. 
network dacnet declared as external, but could not be found.

I can I fix this ?

**Comment by infosecB** [comment]
There are two variables that you must define prior to running `docker-compose up`:

- EXTERNAL_URL
- DEFAULT_PASSWORD

You can either define them in an .env file in same directory as the docker-compose.yml file or you can set them directly inside of the docker-compose.yml file. Set "EXTERNAL_URL" to gitlab and the "DEFAULT_PASSWORD" variable to a password of your choosing. This will be the password used to log into both the Gitlab and Splunk UIs.

See details here: https://docs.docker.com/compose/environment-variables/
